### ISSUE TITLE
Players dislike being able to hear muted player's heros laugh

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#278] opened 2021-06-22 05:26 UTC
![image](https://user-images.githubusercontent.com/63279022/122868416-44426f80-d36e-11eb-82ea-278acce0c826.png)

**Comment by AustraliaIsMyCity** [comment] 2021-06-23 22:59
duplicate of #252

**Closed by AustraliaIsMyCity** 2021-06-23 22:59 UTC
