### ISSUE TITLE
Fix MMR updating when game started with less than 12 players in each team

### ISSUE THREAD

**Issue by AustraliaIsMyCity** [arcadia-redux/12v12#279] opened 2021-06-22 09:27 UTC

**Comment by AustraliaIsMyCity** [comment] 2021-09-07 07:39
if at 2 minutes no player has abandoned the game, it should be counted. if not it should not be counted.

**Comment by Draze22** [comment] 2022-04-28 12:22
Duplicate of #455.

**Closed by Draze22** 2022-04-28 12:22 UTC
Labels: bug, enhancement
