### ISSUE TITLE
linkens

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/12v12#367] opened 2021-09-07 08:26 UTC
perk

Opened from Discord by **non toxic egirl#1202**
Follow the conversation [here](https://discord.com/channels/501306949434867713/828460929427046430/884716119313747978)

**Comment by lovro-m** [comment] 2021-09-07 09:22
Duplicate of https://github.com/arcadia-redux/12v12/issues/366

**Closed** 2021-09-07 09:22 UTC
