### ISSUE TITLE
Several players have reported their items disappearing 

### ISSUE THREAD

**Issue by Draze22** [arcadia-redux/12v12#381] opened 2021-09-15 03:26 UTC
This started after the 13 of September update.

![image](https://user-images.githubusercontent.com/63279022/133365645-a7c358c6-f2ed-433f-a68e-af4a70b86200.png)
![image](https://user-images.githubusercontent.com/63279022/133365660-f9db73a1-a5da-4a7d-b12d-d7180c1f3b2c.png)
![image](https://user-images.githubusercontent.com/63279022/133365671-cbbf8850-b51f-495b-9316-778bf0e2b6d0.png)

**Comment by ZLOY5** [comment] 2021-09-22 09:42
Duplicate of https://github.com/arcadia-redux/12v12/issues/383

**Closed by ZLOY5** 2021-09-22 09:42 UTC
Labels: bug
